name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Elevate wrapper permissions
        run: chmod +x ./gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build Mod
        run: ./gradlew build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZenithProxyMod
          path: build/libs/*.jar
          if-no-files-found: error

      - name: Get Version
        run: echo "MOD_VERSION=$(./gradlew -q printVersion)" >> $GITHUB_ENV

      - name: Github Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.MOD_VERSION }}
          artifacts: "build/libs/*.jar"
          allowUpdates: true
          makeLatest: true
          omitBodyDuringUpdate: true
